name: Update Site via SFTP

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas

      - name: Run update script
        run: python update.py

      - name: Sync files via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 2222
          local_path: './index.html'
          remote_path: '/'
          sftp_only: true
